# Generated by Django 5.0.6 on 2025-10-19 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_site_site_uniq_site_slug_per_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='tenants.site')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_budgets', to='tenants.tenant')),
            ],
        ),
        migrations.AddConstraint(
            model_name='sitebudget',
            constraint=models.UniqueConstraint(fields=('site', 'year', 'month'), name='uniq_site_budget_month'),
        ),
    ]
