# Generated by Django 5.0.6 on 2025-11-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_sitebudget_sitebudget_uniq_site_budget_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='domain',
            field=models.CharField(default='unashe.co.zw', max_length=200),
            preserve_default=False,
        ),
    ]
