# Generated by Django 5.0.6 on 2025-11-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_site_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='domain',
        ),
        migrations.AddField(
            model_name='tenant',
            name='domain',
            field=models.CharField(default='unashe.co.zw', max_length=200),
            preserve_default=False,
        ),
    ]
