# Generated by Django 5.0.6 on 2025-11-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_remove_asset_ticket_asset_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
