# Generated by Django 5.0.6 on 2025-11-06 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_asset_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='unit',
        ),
    ]
