# Generated by Django 5.0.6 on 2025-11-06 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_asset_updated_at_alter_asset_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
