# Generated by Django 5.0.6 on 2025-11-07 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_asset_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Asset Log', 'verbose_name_plural': 'Asset Logs'},
        ),
        migrations.AddField(
            model_name='assetlog',
            name='change',
            field=models.IntegerField(default=1, help_text='Difference in quantity from previous state'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assetlog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assetlog',
            name='quantity',
            field=models.IntegerField(help_text='Current quantity after this change'),
        ),
    ]
