# Generated by Django 5.0.6 on 2025-10-19 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('tenants', '0002_site_site_uniq_site_slug_per_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='tenants.site'),
        ),
    ]
