name: Django CI

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ usercrud ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: backend/requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Prepare env (SQLite dev)
        run: |
          cp .env.example .env || true
          sed -i 's/^DEBUG=true/DEBUG=false/' .env || true

      - name: Run migrations
        run: |
          python manage.py makemigrations --check --noinput || true
          python manage.py migrate --noinput

      - name: Run tests
        run: |
          python manage.py test -v 2
