# Generated by Django 5.0.6 on 2025-11-03 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_remove_asset_file_asset_cost_asset_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetlog',
            name='asset',
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.DeleteModel(
            name='AssetLog',
        ),
    ]
