# Generated by Django 5.0.6 on 2025-11-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_remove_asset_ticket_asset_serial_number'),
        ('tickets', '0004_remove_assetlog_asset_delete_asset_delete_assetlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assets',
            field=models.ManyToManyField(blank=True, related_name='tickets', to='assets.asset'),
        ),
    ]
