# Generated by Django 5.0.6 on 2025-11-05 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_remove_asset_ticket_asset_serial_number'),
        ('tenants', '0005_remove_site_domain_tenant_domain'),
        ('tickets', '0005_ticket_assets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='contractor_feedback',
            field=models.TextField(blank=True, help_text="Feedback about the contractor's work", null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='contractor_rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Rating from 1 to 5', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='follow_up_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='requires_follow_up',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assets',
            field=models.ManyToManyField(blank=True, help_text='Assets related to this ticket', related_name='tickets', to='assets.asset'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assignee',
            field=models.ForeignKey(blank=True, help_text='Contractor assigned to this ticket', limit_choices_to={'is_active_contractor': True, 'role': 'CONTRACTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_by',
            field=models.ForeignKey(help_text='Site Manager who created the ticket', on_delete=django.db.models.deletion.CASCADE, related_name='tickets_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='invoice',
            field=models.FileField(blank=True, help_text='Invoice for the work done', null=True, upload_to='invoices/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='job_card',
            field=models.FileField(blank=True, help_text='Completed job card with work details', null=True, upload_to='job_cards/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Site where the work needs to be done', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tenants.site'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=20),
        ),
    ]
