# Generated by Django 5.0.6 on 2025-11-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_ticket_assigned_at_ticket_closed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='invoice',
            field=models.FileField(blank=True, help_text='Invoice for the work done', null=True, upload_to='media/invoices/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='job_card',
            field=models.FileField(blank=True, help_text='Completed job card with work details', null=True, upload_to='media/job_cards/%Y/%m/%d/'),
        ),
    ]
