# Generated by Django 5.0.6 on 2025-11-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_alter_ticket_invoice_alter_ticket_job_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
