# Generated by Django 5.0.6 on 2025-11-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_ticket_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='invoice_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total amount on the invoice', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='invoice_date',
            field=models.DateField(blank=True, help_text='Date the invoice was issued', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Invoice reference number', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Total cost including all charges', max_digits=12, null=True),
        ),
    ]
